print("Welcome to The band Name Generator?")
print("What city did you grow up in?")
CityName = input()
print("what is the first name of your pet?")
FirstPetName = input()
Bandname = (CityName + " " + FirstPetName)
print("Your band name is", Bandname)